---
galaxy_info:
  author: Steve Fulmer
  description: Role dss_install for stevefulme1.dataiku
  license: GPL-3.0-or-later
  min_ansible_version: '2.16'
  galaxy_tags:
    - dataiku
dependencies: []
